# 站点图标
icon: icon.png

# 标题右上角链接
links:
    Blog: /
    Archive: archives/
    Feed: atom.xml
    About: about/

# 版权显示的起始年份，可选
copyright_startyear: 2021

# 授权协议名和链接
license:
    name: CC BY-SA 4.0 协议
    link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh

# 文章简介长度
excerpt_length: 100

# Archive页面的格式
archive_date_format: MM-DD
