# 站点图标
icon: icon.png

# 标题右上角链接
links:
#    Home: /
#    Archive: archives/
# 链接是否需要大写
links_uppercase: false

# 版权显示的起始年份，可选
#copyright_startyear: 2021

# 授权协议名和链接
license:
    name: CC BY-SA 4.0 协议
    link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh

# 文章自动截取的简介长度
excerpt_length: 200

# Archive页面的格式
archive_date_format: MM-DD
