title: xtex's Blog
subtitle: 'Service Unavailable'
description: xtex's Blog
keywords:
author: xtex
language: zh-cn
timezone: Asia/Shanghai

url: https://xtexx.ml/blog
root: /blog/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false

skip_render:

new_post_name: :YYYY/:MM/:DD-:title.md
auto_spacing: true
external_link:
  enable: true
  field: site
  exclude:
filename_case: 1 # Lower Case File Name
updated_option: date

index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
tag_map:

meta_generator: 
  charset: utf-8

theme: flavor
theme_config:
  icon: icon.png
  links:
    Blog: /
    Archive: archives/
    Random: random.html
    Feed: atom.xml
    About: about/
  links_uppercase: true
  copyright_startyear: 2021
  license:
    name: CC BY-SA 4.0 协议
    link: https://creativecommons.org/licenses/by-sa/4.0/deed.zh
  excerpt_length: 200
  archive_date_format: MM-DD
  before_body_end: '
"<script>var _hmt = _hmt || [];(function() {var hm = document.createElement(\"script\");
hm.src = \"https://hm.baidu.com/hm.js?65f3d3b959460c6941d7d6a797086e30\";
document.getElementsByTagName(\"script\")[0].parentNode.insertBefore(hm, s); 
})();
</script>"
  '

sitemap:
  tags: true
  categories: true

alias:
  github: https://github.com/xtexChooser/blog/

feed:
  type: [ atom, rss2 ]
  path: [ atom.xml, feed.xml ]
  limit: 20

archive_generator:
  per_page: 30
  yearly: true
  monthly: true

relative_link: true

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '''""'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: '_'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: '§ '

all_minifier: true
js_concator:
  enable: false
html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude: []
css_minifier:
  enable: true
  silent: false
  exclude: []
js_minifier:
  enable: true
  mangle: true
  silent: false
  exclude: []
image_minifier:
  enable: false

kroki:
  server: "https://kroki.io/"
  link: "localLink"
  outputFormat: "svg"
  className: 'kroki'
  inserts:
    - diagram: plantuml
      after: 1
      # see https://plantuml.com/en/theme
      fragment: '!theme sketchy-outline'
    - diagram: mermaid
      after: 0
      # see https://mermaid-js.github.io/mermaid/#/theming
      fragment: "%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ff0000'}}}%%"
