name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: public
          path: public

      - name: Tencent Cloud COS Action
        uses: TencentCloud/cos-action@v1
        if: github.event_name == 'push'
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public
          remote_path: blog
          clean: true
